// <auto-generated />
using CrossPlay.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CrossPlay.Migrations
{
    [DbContext(typeof(CrossPlayContext))]
    partial class CrossPlayContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("CrossPlay.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Action"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "RPG"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Indie"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Strategy"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Sports"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Arcade"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Card & Board Game"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Racing"
                        });
                });

            modelBuilder.Entity("CrossPlay.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("GameName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Link")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("GameId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            GameName = "Operation: Tango",
                            Link = "http://www.operation-tango.com/"
                        },
                        new
                        {
                            GameId = 2,
                            GameName = "Hunter's Arena: Legends",
                            Link = "https://store.steampowered.com/news/app/1061100/view/2997690640726279509"
                        },
                        new
                        {
                            GameId = 3,
                            GameName = "Godfall",
                            Link = "https://www.godfall.com/"
                        },
                        new
                        {
                            GameId = 4,
                            GameName = "Blightbound",
                            Link = "https://store.steampowered.com/news/app/1263070/view/2971794942848931181"
                        },
                        new
                        {
                            GameId = 5,
                            GameName = "Dungeons & Dragons: Dark Alliance",
                            Link = "https://www.darkalliance.com/"
                        },
                        new
                        {
                            GameId = 6,
                            GameName = "Overwatch",
                            Link = "http://battle.net/overwatch/"
                        },
                        new
                        {
                            GameId = 7,
                            GameName = "Trailmakers",
                            Link = "http://www.playtrailmakers.com/"
                        },
                        new
                        {
                            GameId = 8,
                            GameName = "Football Manager 2021: Xbox Edition",
                            Link = "https://www.footballmanager.com/games/football-manager-2021-xbox"
                        },
                        new
                        {
                            GameId = 9,
                            GameName = "Bleeding Edge",
                            Link = "https://www.bleedingedge.com/"
                        },
                        new
                        {
                            GameId = 10,
                            GameName = "Destiny 2",
                            Link = "https://www.destinythegame.com/"
                        },
                        new
                        {
                            GameId = 11,
                            GameName = "Rust: Console Edition",
                            Link = "https://gamingbolt.com/rust-console-edition-7-things-you-need-to-know"
                        },
                        new
                        {
                            GameId = 12,
                            GameName = "Human: Fall Flat",
                            Link = "http://www.nobrakesgames.com/human/"
                        },
                        new
                        {
                            GameId = 13,
                            GameName = "Enlisted",
                            Link = "https://enlisted.net/"
                        },
                        new
                        {
                            GameId = 14,
                            GameName = "Chivalry 2",
                            Link = "https://www.chivalry2.com/"
                        },
                        new
                        {
                            GameId = 15,
                            GameName = "Predator: Hunting Grounds",
                            Link = "https://www.gamerevolution.com/guides/644342-predator-hunting-grounds-crossplay-invites"
                        });
                });

            modelBuilder.Entity("CrossPlay.Models.GameCategory", b =>
                {
                    b.Property<int>("GameCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.HasKey("GameCategoryId");

                    b.ToTable("GameCategories");

                    b.HasData(
                        new
                        {
                            GameCategoryId = 1,
                            CategoryId = 4,
                            GameId = 1
                        },
                        new
                        {
                            GameCategoryId = 2,
                            CategoryId = 2,
                            GameId = 2
                        },
                        new
                        {
                            GameCategoryId = 3,
                            CategoryId = 2,
                            GameId = 3
                        },
                        new
                        {
                            GameCategoryId = 4,
                            CategoryId = 2,
                            GameId = 4
                        },
                        new
                        {
                            GameCategoryId = 5,
                            CategoryId = 2,
                            GameId = 5
                        },
                        new
                        {
                            GameCategoryId = 6,
                            CategoryId = 1,
                            GameId = 6
                        },
                        new
                        {
                            GameCategoryId = 7,
                            CategoryId = 8,
                            GameId = 7
                        },
                        new
                        {
                            GameCategoryId = 8,
                            CategoryId = 5,
                            GameId = 8
                        },
                        new
                        {
                            GameCategoryId = 9,
                            CategoryId = 1,
                            GameId = 9
                        },
                        new
                        {
                            GameCategoryId = 10,
                            CategoryId = 1,
                            GameId = 10
                        },
                        new
                        {
                            GameCategoryId = 11,
                            CategoryId = 3,
                            GameId = 11
                        },
                        new
                        {
                            GameCategoryId = 12,
                            CategoryId = 3,
                            GameId = 12
                        },
                        new
                        {
                            GameCategoryId = 13,
                            CategoryId = 1,
                            GameId = 13
                        },
                        new
                        {
                            GameCategoryId = 14,
                            CategoryId = 1,
                            GameId = 14
                        },
                        new
                        {
                            GameCategoryId = 15,
                            CategoryId = 1,
                            GameId = 15
                        });
                });

            modelBuilder.Entity("CrossPlay.Models.GamePlatform", b =>
                {
                    b.Property<int>("GamePlatformId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int");

                    b.HasKey("GamePlatformId");

                    b.ToTable("GamePlatforms");

                    b.HasData(
                        new
                        {
                            GamePlatformId = 1,
                            GameId = 1,
                            PlatformId = 1
                        },
                        new
                        {
                            GamePlatformId = 2,
                            GameId = 1,
                            PlatformId = 2
                        },
                        new
                        {
                            GamePlatformId = 3,
                            GameId = 1,
                            PlatformId = 11
                        },
                        new
                        {
                            GamePlatformId = 4,
                            GameId = 1,
                            PlatformId = 3
                        },
                        new
                        {
                            GamePlatformId = 5,
                            GameId = 1,
                            PlatformId = 10
                        },
                        new
                        {
                            GamePlatformId = 6,
                            GameId = 2,
                            PlatformId = 1
                        },
                        new
                        {
                            GamePlatformId = 7,
                            GameId = 2,
                            PlatformId = 2
                        },
                        new
                        {
                            GamePlatformId = 8,
                            GameId = 2,
                            PlatformId = 11
                        },
                        new
                        {
                            GamePlatformId = 9,
                            GameId = 3,
                            PlatformId = 2
                        },
                        new
                        {
                            GamePlatformId = 10,
                            GameId = 3,
                            PlatformId = 11
                        },
                        new
                        {
                            GamePlatformId = 11,
                            GameId = 4,
                            PlatformId = 1
                        },
                        new
                        {
                            GamePlatformId = 12,
                            GameId = 4,
                            PlatformId = 2
                        },
                        new
                        {
                            GamePlatformId = 13,
                            GameId = 4,
                            PlatformId = 3
                        },
                        new
                        {
                            GamePlatformId = 14,
                            GameId = 5,
                            PlatformId = 1
                        },
                        new
                        {
                            GamePlatformId = 15,
                            GameId = 5,
                            PlatformId = 10
                        },
                        new
                        {
                            GamePlatformId = 16,
                            GameId = 5,
                            PlatformId = 3
                        },
                        new
                        {
                            GamePlatformId = 17,
                            GameId = 6,
                            PlatformId = 1
                        },
                        new
                        {
                            GamePlatformId = 18,
                            GameId = 6,
                            PlatformId = 2
                        },
                        new
                        {
                            GamePlatformId = 19,
                            GameId = 6,
                            PlatformId = 11
                        },
                        new
                        {
                            GamePlatformId = 20,
                            GameId = 6,
                            PlatformId = 5
                        },
                        new
                        {
                            GamePlatformId = 21,
                            GameId = 6,
                            PlatformId = 3
                        },
                        new
                        {
                            GamePlatformId = 22,
                            GameId = 6,
                            PlatformId = 10
                        },
                        new
                        {
                            GamePlatformId = 23,
                            GameId = 7,
                            PlatformId = 1
                        },
                        new
                        {
                            GamePlatformId = 24,
                            GameId = 7,
                            PlatformId = 3
                        },
                        new
                        {
                            GamePlatformId = 25,
                            GameId = 7,
                            PlatformId = 10
                        },
                        new
                        {
                            GamePlatformId = 26,
                            GameId = 8,
                            PlatformId = 1
                        },
                        new
                        {
                            GamePlatformId = 27,
                            GameId = 8,
                            PlatformId = 3
                        },
                        new
                        {
                            GamePlatformId = 28,
                            GameId = 8,
                            PlatformId = 10
                        },
                        new
                        {
                            GamePlatformId = 29,
                            GameId = 9,
                            PlatformId = 1
                        },
                        new
                        {
                            GamePlatformId = 30,
                            GameId = 9,
                            PlatformId = 3
                        },
                        new
                        {
                            GamePlatformId = 31,
                            GameId = 10,
                            PlatformId = 1
                        },
                        new
                        {
                            GamePlatformId = 32,
                            GameId = 10,
                            PlatformId = 2
                        },
                        new
                        {
                            GamePlatformId = 33,
                            GameId = 10,
                            PlatformId = 11
                        },
                        new
                        {
                            GamePlatformId = 34,
                            GameId = 10,
                            PlatformId = 3
                        },
                        new
                        {
                            GamePlatformId = 35,
                            GameId = 10,
                            PlatformId = 10
                        },
                        new
                        {
                            GamePlatformId = 36,
                            GameId = 11,
                            PlatformId = 2
                        },
                        new
                        {
                            GamePlatformId = 37,
                            GameId = 11,
                            PlatformId = 11
                        },
                        new
                        {
                            GamePlatformId = 38,
                            GameId = 11,
                            PlatformId = 3
                        },
                        new
                        {
                            GamePlatformId = 39,
                            GameId = 11,
                            PlatformId = 10
                        },
                        new
                        {
                            GamePlatformId = 40,
                            GameId = 12,
                            PlatformId = 1
                        },
                        new
                        {
                            GamePlatformId = 41,
                            GameId = 12,
                            PlatformId = 3
                        },
                        new
                        {
                            GamePlatformId = 42,
                            GameId = 12,
                            PlatformId = 10
                        },
                        new
                        {
                            GamePlatformId = 43,
                            GameId = 13,
                            PlatformId = 1
                        },
                        new
                        {
                            GamePlatformId = 44,
                            GameId = 13,
                            PlatformId = 11
                        },
                        new
                        {
                            GamePlatformId = 45,
                            GameId = 13,
                            PlatformId = 10
                        },
                        new
                        {
                            GamePlatformId = 46,
                            GameId = 14,
                            PlatformId = 1
                        },
                        new
                        {
                            GamePlatformId = 47,
                            GameId = 14,
                            PlatformId = 2
                        },
                        new
                        {
                            GamePlatformId = 48,
                            GameId = 14,
                            PlatformId = 11
                        },
                        new
                        {
                            GamePlatformId = 49,
                            GameId = 14,
                            PlatformId = 3
                        },
                        new
                        {
                            GamePlatformId = 50,
                            GameId = 14,
                            PlatformId = 10
                        },
                        new
                        {
                            GamePlatformId = 51,
                            GameId = 15,
                            PlatformId = 1
                        },
                        new
                        {
                            GamePlatformId = 52,
                            GameId = 15,
                            PlatformId = 2
                        });
                });

            modelBuilder.Entity("CrossPlay.Models.Platform", b =>
                {
                    b.Property<int>("PlatformId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("PlatformName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("PlatformId");

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            PlatformId = 1,
                            PlatformName = "Windows"
                        },
                        new
                        {
                            PlatformId = 2,
                            PlatformName = "Playstation 4"
                        },
                        new
                        {
                            PlatformId = 3,
                            PlatformName = "Xbox One"
                        },
                        new
                        {
                            PlatformId = 4,
                            PlatformName = "Mac"
                        },
                        new
                        {
                            PlatformId = 5,
                            PlatformName = "Switch"
                        },
                        new
                        {
                            PlatformId = 6,
                            PlatformName = "Playstation Vita 6"
                        },
                        new
                        {
                            PlatformId = 7,
                            PlatformName = "Playstation 3"
                        },
                        new
                        {
                            PlatformId = 8,
                            PlatformName = "iOS"
                        },
                        new
                        {
                            PlatformId = 9,
                            PlatformName = "Android"
                        },
                        new
                        {
                            PlatformId = 10,
                            PlatformName = "Xbox Series X/S"
                        },
                        new
                        {
                            PlatformId = 11,
                            PlatformName = "Playstation 5"
                        },
                        new
                        {
                            PlatformId = 12,
                            PlatformName = "Linux"
                        },
                        new
                        {
                            PlatformId = 13,
                            PlatformName = "Wii"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
